### ISSUE TITLE
Conflicting documentation regarding Infra

### ISSUE THREAD

**Issue by alberreman** [daostack/DAOstack-Hackers-Kit#14]
The Hacker's Kit documentation doesn't make it clear that Infra is a subset of Arc, and that Arc contains voting machines/ everything that infra does - instead it seems almost like infra is the layer below arc/ that arc is reliant upon infra. In other words, the relationship between infra and arc could be improved for clarity.

**Comment by shivgupt** [comment]
Infra is not a subset of Arc and the documentation has been updated now
