### ISSUE TITLE
Trying to run `truffle migrate --network kovan-infura`

### ISSUE THREAD

**Issue by mehranhydary** [daostack/DAOstack-Hackers-Kit#15]
I keep getting the following error: 

`Arc.js (error): InitializeArcJs failed: Error: Utils.getWeb3: web3 is not connected to a net
Error: InitializeArcJs failed: Error: Utils.getWeb3: web3 is not connected to a net
    at Object.<anonymous> (REDACTED/node_modules/@daostack/arc.js/lib/index.ts:218:11)
    at Generator.throw (<anonymous>)
    at rejected (REDACTED/node_modules/tslib/tslib.js:105:69)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Truffle v5.0.0 (core: 5.0.0)`

**Comment by mehranhydary** [comment]
I'm also having this issue for the "peepeth-dao-example"

**Comment by mehranhydary** [comment]
Full log: 
'
mehran:peepeth-dao-example mehranhydary$ yarn install
yarn install v1.12.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning @daostack/arc.js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning @daostack/arc.js > @daostack/migration > web3 > web3-bzz > swarm-js > fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
warning @daostack/arc.js > @daostack/migration > web3 > web3-bzz > swarm-js > tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
warning truffle-hdwallet-provider > web3-provider-engine > ethereumjs-block > merkle-patricia-tree > level-ws > xtend > object-keys@0.4.0: 
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @daostack/arc@0.0.0-alpha.58" has unmet peer dependency "ganache-cli@^6.2.3".
warning "@daostack/arc > @daostack/infra@0.0.0-alpha.10" has unmet peer dependency "ganache-cli@^6.2.3".
warning " > truffle-hdwallet-provider@0.0.6" has incorrect peer dependency "truffle@4.x".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.13.0", while you're on "1.12.3".
info To upgrade, run the following command:
$ brew upgrade yarn
✨  Done in 150.28s.
mehran:peepeth-dao-example mehranhydary$ truffle migrate --network kovan-infura
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/PeepScheme.sol...
Compiling ./contracts/Peepeth.sol...
Compiling ./contracts/PeepethInterface.sol...
Compiling @daostack/arc/contracts/controller/Avatar.sol...
Compiling @daostack/arc/contracts/controller/Controller.sol...
Compiling @daostack/arc/contracts/controller/ControllerInterface.sol...
Compiling @daostack/arc/contracts/controller/DAOToken.sol...
Compiling @daostack/arc/contracts/globalConstraints/GlobalConstraintInterface.sol...
Compiling @daostack/arc/contracts/token/ERC827/ERC827.sol...
Compiling @daostack/arc/contracts/token/ERC827/ERC827Token.sol...
Compiling @daostack/arc/contracts/universalSchemes/UniversalScheme.sol...
Compiling @daostack/arc/contracts/universalSchemes/UniversalSchemeInterface.sol...
Compiling @daostack/arc/contracts/votingMachines/VotingMachineCallbacks.sol...
Compiling @daostack/infra/contracts/Reputation.sol...
Compiling @daostack/infra/contracts/libs/OrderStatisticTree.sol...
Compiling @daostack/infra/contracts/libs/RealMath.sol...
Compiling @daostack/infra/contracts/votingMachines/GenesisProtocol.sol...
Compiling @daostack/infra/contracts/votingMachines/IntVoteInterface.sol...
Compiling @daostack/infra/contracts/votingMachines/ProposalExecuteInterface.sol...
Compiling @daostack/infra/contracts/votingMachines/VotingMachineCallbacksInterface.sol...
Compiling openzeppelin-solidity/contracts/ECRecovery.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/BasicToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/BurnableToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Basic.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/SafeERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol...
Writing artifacts to ./build/contracts

⚠️  Important ⚠️
If you're using an HDWalletProvider, it must be Web3 1.0 enabled or your migration will hang.
Try: npm install --save truffle-hdwallet-provider@web3-one


Migrations dry-run (simulation)
===============================
> Network name:    'kovan-infura-fork'
> Network id:      42
> Block gas limit: 8000000


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > account:             0xdBcf538233d02B033104b519b83E3185634322cA
   > balance:             0.40510209127452112
   > gas used:            262462
   > gas price:           1 gwei
   > value sent:          0 ETH
   > total cost:          0.000262462 ETH

   -------------------------------------
   > Total cost:         0.000262462 ETH


2_deploy_dao.js
===============
Arc.js (error): InitializeArcJs failed: Error: Utils.getWeb3: web3 is not connected to a net
Error: InitializeArcJs failed: Error: Utils.getWeb3: web3 is not connected to a net
    at Object.<anonymous> (/Users/mehranhydary/Desktop/unicef/dev/daostack/DAOstack-Hackers-Kit/peepeth-dao-example/node_modules/@daostack/arc.js/lib/index.ts:218:11)
    at Generator.throw (<anonymous>)
    at rejected (/Users/mehranhydary/Desktop/unicef/dev/daostack/DAOstack-Hackers-Kit/peepeth-dao-example/node_modules/tslib/tslib.js:105:69)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Truffle v5.0.0 (core: 5.0.0)
Node v11.6.0
'

**Comment by ben-kaufman** [comment]
Hi @mehranhydary,
Did you follow the instruction here? https://github.com/daostack/DAOstack-Hackers-Kit/tree/master/peepeth-dao-example#deploy-and-use-on-kovan-network

Specifically configuring this file: https://github.com/daostack/DAOstack-Hackers-Kit/blob/master/peepeth-dao-example/truffle.js

**Comment by mehranhydary** [comment]
Hi @ben-kaufman, 

Yes I updated the truffle.js file with seed key and infura url

**Comment by shivgupt** [comment]
Have updated to use the latest migration tool - '@daostack/migration' and this issue is not relevant any more.
