### ISSUE TITLE
MVP Contribution example

### ISSUE THREAD

**Issue by orenyodfat** [daostack/DAOstack-Hackers-Kit#20]
- [x] new scheme
- [x] Deploying a dao
- [x] Indexing dao
- [x] Thin client layer
- [x] Front end example over the client.
- [x] All should be dockerized , running on local machine
- [x] Documentation

**Comment by shivgupt** [comment]
What all should we include in the front-end example of the MVP?
  - list of DAOs from subgraph
  - create/browse proposal using client
  - vote/stake on proposals
Anything else?

**Comment by shivgupt** [comment]
What all should we include in the front-end example of the MVP?
  - list of DAOs from subgraph
  - create/browse proposal using client
  - vote/stake on proposals
Anything else?

**Comment by shivgupt** [comment]
MVP contribution example have been updated
